spring:
  application:
   name: order-service
  config:
      import: optional:configserver:http://localhost:9090

application:
  config:
    customer-url: http://localhost:8090/api/v1/customers
    product-url: http://localhost:8050/api/v1/products
    payment-url: http://localhost:8060/api/v1/payments

